<?php

#####################################################
#	jargon version 1.0 pour xoops 2.X
#	Copyright 2004, Martial Le Peillet
#	webmaster@toplenet.com - http://www.toplenet.com
#
#	Module Original :
#	jargon version 1.6 pour xoops 1.0 RC3
#	Copyright © 2002, Pascal Le Boustouller
#
#  Licence : GPL
#  Merci de laisser ce copyright en place...
#####################################################
// Translation Info
// *************************************************************** //
// ############################################################### //
// ## underpop 2.0.7 - Brazilian Portuguese Translation		## //
// ############################################################### //
// ## Translator.....: Mikhail Miguel				## //
// ## E-mail.........: mikhail@ajato.com.br			## //
// ## Website.......: http://xoops.eti.br			## //
// ############################################################### //
// *************************************************************** //
$modversion['name'] = _MI_GLO_NAME;
$modversion['version'] = 1.0;
$modversion['description'] = _MI_GLO_DESC;
$modversion['credits'] = 'Module original : Pascal Le Boustoufler - V1.6 <br> Martial Le Peillet - toplenet.com - Ajout de cat&eacute;gories V2.0';
$modversion['author'] = 'Mikhail Miguel - mikhail@ajato.com.br';
$modversion['help'] = 'jargon.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'slogo_jargon.png';
$modversion['dirname'] = 'jargon';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Blocks
$modversion['blocks'][1]['file'] = 'jargon_rand.php';
$modversion['blocks'][1]['name'] = _MI_GLO_BNAME1;
$modversion['blocks'][1]['show_func'] = 'jargon_showrand';

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _PRODEF;
$modversion['sub'][1]['url'] = 'index.php?pa=Propose';
$modversion['sub'][2]['name'] = _ASKDEF;
$modversion['sub'][2]['url'] = 'index.php?pa=Demande';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix! - permet la suppression des tables à la désinstallation du module.)
$modversion['tables'][0] = 'jargon';
$modversion['tables'][1] = 'jargon_cat';
$modversion['tables'][2] = 'jargon_comm';

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'jargon_search';
